#!/usr/bin/env python3
"""Bundle the site's local CSS and JS into two hashed files.

  index.src.html  -> editable source (individual <link>/<script> tags)
  index.html      -> GENERATED: same page with site.<hash>.css / .js
  site.<hash>.css / site.<hash>.js -> generated bundles at the root (relative url(assets/…) must keep resolving)

Run `python3 build.py` before committing. Order of files is taken from
index.src.html, so the cascade and script order are unchanged.
"""
import hashlib, os, re, glob

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, "index.src.html")
OUT = os.path.join(ROOT, "index.html")
DIST = ROOT  # bundles live at the root so url(assets/…) in CSS keeps resolving

html = open(SRC, encoding="utf-8").read()

css_tag = re.compile(r'[ \t]*<link rel="stylesheet" href="(?!https?://)([^"?]+\.css)(?:\?v=\d+)?" />\n?')
js_tag  = re.compile(r'[ \t]*<script src="(?!https?://)([^"?]+\.js)(?:\?v=\d+)?"></script>\n?')

css_files = css_tag.findall(html)
js_files  = js_tag.findall(html)

def strip_css_comments(text):
    # remove /* … */ comments only when not inside a string
    out, i, n = [], 0, len(text)
    quote = None
    while i < n:
        c = text[i]
        if quote:
            out.append(c)
            if c == "\\" and i + 1 < n:
                out.append(text[i+1]); i += 2; continue
            if c == quote: quote = None
            i += 1; continue
        if c in ("'", '"'):
            quote = c; out.append(c); i += 1; continue
        if text.startswith("/*", i):
            j = text.find("*/", i + 2)
            i = n if j < 0 else j + 2
            continue
        out.append(c); i += 1
    s = "".join(out)
    s = re.sub(r"\n[ \t]+", "\n", s)      # leading indentation
    s = re.sub(r"\n{2,}", "\n", s)        # blank lines
    return s

css_parts = []
for f in css_files:
    body = open(os.path.join(ROOT, f), encoding="utf-8").read()
    css_parts.append(f"/* ===== {f} ===== */\n" + strip_css_comments(body))
css_bundle = "\n".join(css_parts)

js_parts = []
for f in js_files:
    body = open(os.path.join(ROOT, f), encoding="utf-8").read()
    js_parts.append(f"/* ===== {f} ===== */\n" + body.rstrip() + "\n;")
js_bundle = "\n".join(js_parts)

os.makedirs(DIST, exist_ok=True)
for old in glob.glob(os.path.join(DIST, "site.*")):
    try: os.remove(old)
    except OSError: pass  # sandboxed shells may not allow deletes; stale files are harmless

def write(kind, content):
    h = hashlib.md5(content.encode("utf-8")).hexdigest()[:8]
    name = f"site.{h}.{kind}"
    open(os.path.join(DIST, name), "w", encoding="utf-8").write(content)
    return name

css_name = write("css", css_bundle)
js_name  = write("js", js_bundle)

# Replace the first tag of each kind with the bundle, drop the rest.
first = [True]
def css_sub(m):
    if first[0]:
        first[0] = False
        return f'  <link rel="stylesheet" href="{css_name}" />\n'
    return ""
out = css_tag.sub(css_sub, html)
first[0] = True
def js_sub(m):
    if first[0]:
        first[0] = False
        return f'  <script src="{js_name}"></script>\n'
    return ""
out = js_tag.sub(js_sub, out)
out = out.replace("<!doctype html>", "<!doctype html>\n<!-- GENERATED by build.py from index.src.html — edit index.src.html, then run: python3 build.py -->", 1)
open(OUT, "w", encoding="utf-8").write(out)

print(f"css: {len(css_files)} files -> {css_name} ({len(css_bundle)//1024} KB)")
print(f"js : {len(js_files)} files -> {js_name} ({len(js_bundle)//1024} KB)")
